name: devmobile
description: "A new Flutter project."

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.4.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  url_launcher: ^6.3.2
  http: ^0.13.6  # Version compatible avec flutter_mjpeg
  video_player: ^2.10.0
  provider: ^6.0.5
  flutter_mjpeg: ^2.0.4
  better_player: ^0.4.84

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true